dist: xenial
sudo: required
language:
  - cpp
compiler:
  - gcc
  - clang
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc
      - cmake
      - clang
before_install:
  - sudo apt-get install -y liblua5.1-dev build-essential 
script: cd examples && make

