dist: bionic
sudo: required
language:
  - cpp
compiler:
  - gcc
  - clang
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-7
      - g++-7
      - cmake
      - clang-7
before_install:
  - sudo apt-get install -y liblua5.1-dev clang build-essential 
script: cd examples && make

